name: PR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x

    - name: Build Extension (win-x64)
      run: dotnet publish MapExportExtension/MapExportExtension.csproj -c Release -r win-x64 -o "./@arma3MapExporter"

    - name: Build Launcher (win-x64)
      run: dotnet publish MapExportLauncher/MapExportLauncher.csproj -c Release -r win-x64 -o "bin"

    - name: Create archive for Launcher
      shell: pwsh
      run: Compress-Archive bin/* MapExportLauncher.zip
      
    - uses: arma-actions/hemtt@v1
      name: Setup HEMTT

    - name: Build Mod
      run: hemtt build
      working-directory: "./@arma3MapExporter"
