name: Release

on:
  release:
    types: [ "published" ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 10.0.x

    - name: Build Extension (win-x64)
      run: dotnet publish MapExportExtension/MapExportExtension.csproj -c Release -r win-x64 -o "@arma3MapExporter"

    - name: Build Launcher (win-x64)
      run: dotnet publish MapExportLauncher/MapExportLauncher.csproj -c Release -r win-x64 -o "bin"

    - name: Create archive for Launcher
      shell: pwsh
      run: Compress-Archive bin/* MapExportLauncher.zip
      
    - uses: arma-actions/hemtt@v1
      name: Setup HEMTT

    - name: Build Mod
      run: hemtt release
      working-directory: "@arma3MapExporter"
        
    - uses: Shopify/upload-to-release@master
      with:
        name: a3me.zip
        path: "@arma3MapExporter/releases/a3me-latest.zip"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        content-type: application/zip

    - uses: Shopify/upload-to-release@master
      with:
        name: MapExportLauncher.zip
        path: "MapExportLauncher.zip"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        content-type: application/zip

